// <auto-generated>
// RgiSequenceFinder.TableGenerator
// </auto-generated>

namespace RgiSequenceFinder
{
    partial class RgiTable
    {
        private static int FindTag(TagSequence tags)
        {
            switch (tags.LongValue)
            {
                case 0x7F676E656267UL: return 642;
                case 0x7F7463736267UL: return 643;
                case 0x7F736C776267UL: return 644;
                default: return -1;
            }
        }
    }
}
