// <auto-generated>
// RgiSequenceFinder.TableGenerator
// </auto-generated>

namespace RgiSequenceFinder
{
    partial class RgiTable
    {
        private static int FindKeycap(Keycap key)
        {
            switch (key.Value)
            {
                case (byte)'#': return 0;
                case (byte)'*': return 1;
                case (byte)'0': return 2;
                case (byte)'1': return 3;
                case (byte)'2': return 4;
                case (byte)'3': return 5;
                case (byte)'4': return 6;
                case (byte)'5': return 7;
                case (byte)'6': return 8;
                case (byte)'7': return 9;
                case (byte)'8': return 10;
                case (byte)'9': return 11;
                default: return -1;
            }
        }
    }
}
